version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "bigmichi1"
    labels:
      - "dependencies"
      - "automerge"
      - "github-actions"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "bigmichi1"
    labels:
      - "dependencies"
      - "automerge"
      - "docker"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "automerge"
      - "npm"
